version: "3.8"

services:
  # sut Automated Repository Test
  # see https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: ["/bin/sh", "-c", "which ab && which bash && which fping && which macchanger && which mtr && which nc && which ngrep && which nmap && which netstat && which libressl && which drill && which curl && which git && which find && which python3 && python3 -c 'import requests'"]
