version: "3.7"

services:
  # sut Automated Repository Test
  # see https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: ["/bin/sh", "-c", "which bash && which fping && which macchanger && which nc && which ngrep && which nmap && which netstat && which libressl"]
